#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

random_key=$(ynh_string_random --length=32)
email=$(ynh_user_get_info --username=$admin --key=mail)
timezone=$(cat /etc/timezone)
ynh_app_setting_set --app=$app --key=random_key --value=$random_key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

ynh_setup_source --dest_dir=$install_dir

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
chmod -R 775 $install_dir/storage

#=================================================
# SYSTEL CONFIGURATIONS
#=================================================

ynh_script_progression --message="Add system configurations related to $app..."

ynh_add_fpm_config

ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding $app configuration..."

ynh_add_config --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown $app "$install_dir/.env"

#=================================================
# DEPLOY
#=================================================
ynh_script_progression --message="Deploying..."

pushd "$install_dir"
    php$phpversion artisan firefly-iii:upgrade-database
    php$phpversion artisan firefly-iii:correct-database
    php$phpversion artisan firefly-iii:report-integrity
    php$phpversion artisan firefly-iii:laravel-passport-keys
popd

#=================================================
# SETUP A CRON
#=================================================
ynh_script_progression --message="Setuping a cron..."

ynh_add_config --template="cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
