#!/bin/bash

source /usr/share/yunohost/helpers

email=$(ynh_user_get_info --username=$admin --key=mail)
timezone="$(timedatectl show --value --property=Timezone)"

ynh_app_setting_set_default --key=language --value="en_US"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env storage"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# FIXUP OAUTH KEY PERMISSIONS
#=================================================

if [ -f "$install_dir/storage/oauth-private.key" ]; then
  chown $app:$app $install_dir/storage/oauth-{public,private}.key
fi

#=================================================
# DEPLOYMENT
#=================================================
ynh_script_progression "Upgrading database..."

pushd "$install_dir"
    ynh_exec_as_app php$php_version artisan migrate --seed
    ynh_exec_as_app php$php_version artisan upgrade:480-decrypt-all
    ynh_exec_as_app php$php_version artisan cache:clear
    ynh_exec_as_app php$php_version artisan firefly-iii:upgrade-database
    ynh_exec_as_app php$php_version artisan passport:keys || true
    ynh_exec_as_app php$php_version artisan cache:clear
    ynh_exec_as_app php$php_version artisan view:clear
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
